export default () => ({
  accounts: [
    {
      id: 1,
      name: 'Готівка',
      balance: 2,
      icon: 'wallet',
      color: 'green',
      currency: 'UAH',
      currency_display: 'symbol',
      account_type_id: 1,
      is_active: true,
    },
    {
      id: 2,
      name: 'Готівка',
      balance: -100000,
      icon: 'card',
      color: 'green',
      currency: 'UAH',
      currency_display: 'code',
      account_type_id: 1,
      is_active: true,
    },
    {
      id: 3,
      name: 'Готівка',
      balance: -100000,
      icon: 'wallet',
      color: 'gryen',
      currency: 'UAH',
      currency_display: 'name',
      account_type_id: 1,
      is_active: true,
    },
    {
      id: 4,
      name: 'Готівка',
      balance: 100000,
      icon: 'wallet',
      color: 'yellow',
      currency: 'UAH',
      currency_display: 'narrowSymbol',
      account_type_id: 1,
      is_active: true,
    },
    {
      id: 5,
      name: 'Готівка',
      balance: 100000,
      icon: 'wallet',
      color: 'orange',
      currency: 'UAH',
      currency_display: 'narrowSymbol',
      account_type_id: 2,
      is_active: true,
    },
    {
      id: 6,
      name: 'Готівка',
      balance: -100000,
      icon: 'wallet',
      color: 'red',
      currency: 'UAH',
      currency_display: 'narrowSymbol',
      account_type_id: 3,
      is_active: true,
    },
  ],

  currency: Intl.supportedValuesOf('currency'),
  currency_display: [
    { value: 'symbol', label: 'Скорочення (грн)' },
    { value: 'code', label: 'Код (UAH)' },
    { value: 'name', label: 'Назва (українських гривень)' },
    { value: 'narrowSymbol', label: 'Символ (₴' },
  ],

  account_type_id: [
    { value: 1, label: 'Рахунки' },
    { value: 2, label: 'Заощадження' },
    { value: 3, label: 'Борги' },
  ],
})
