/**
 * Rates for all of these come from open.er-api.com (see `db/exchangeRates.ts`)
 * — a free, no-key service with UAH as a base, covering the ~160 currencies
 * it quotes. Deliberately excludes: RUB (not offered as a display/account
 * currency in this app), a few IMF/precious-metal accounting units that
 * aren't real spendable currencies (XDR, XAG, XAU, XPD, XPT, CLF), CNH
 * (offshore-market duplicate of CNY), and SLL/ZWL/HRK (currencies their own
 * countries have already replaced — with SLE, ZWG, and EUR respectively).
 */
export const COMMON_CURRENCIES = [
  { code: 'UAH', label: 'Гривня (UAH)' },
  { code: 'USD', label: 'Долар США (USD)' },
  { code: 'EUR', label: 'Євро (EUR)' },
  { code: 'GBP', label: 'Фунт стерлінгів (GBP)' },
  { code: 'PLN', label: 'Злотий (PLN)' },
  { code: 'CZK', label: 'Чеська крона (CZK)' },
  { code: 'CHF', label: 'Швейцарський франк (CHF)' },
  { code: 'CAD', label: 'Канадський долар (CAD)' },
  { code: 'AUD', label: 'Австралійський долар (AUD)' },
  { code: 'NZD', label: 'Новозеландський долар (NZD)' },
  { code: 'JPY', label: 'Єна (JPY)' },
  { code: 'CNY', label: 'Юань Женьміньбі (CNY)' },
  { code: 'HKD', label: 'Гонконгівський долар (HKD)' },
  { code: 'SGD', label: 'Сінгапурський долар (SGD)' },
  { code: 'KRW', label: 'Вона (KRW)' },
  { code: 'INR', label: 'Індійська рупія (INR)' },
  { code: 'TRY', label: 'Турецька ліра (TRY)' },
  { code: 'ILS', label: 'Новий ізраїльський шекель (ILS)' },
  { code: 'AED', label: 'Дирхам ОАЕ (AED)' },
  { code: 'SAR', label: 'Саудівський ріял (SAR)' },
  { code: 'SEK', label: 'Шведська крона (SEK)' },
  { code: 'NOK', label: 'Норвезька крона (NOK)' },
  { code: 'DKK', label: 'Данська крона (DKK)' },
  { code: 'HUF', label: 'Форинт (HUF)' },
  { code: 'RON', label: 'Румунський лей (RON)' },
  { code: 'RSD', label: 'Сербський динар (RSD)' },
  { code: 'GEL', label: 'Ларі (GEL)' },
  { code: 'AZN', label: 'Азербайджанський манат (AZN)' },
  { code: 'KZT', label: 'Теньге (KZT)' },
  { code: 'MDL', label: 'Молдовський лей (MDL)' },
  { code: 'MXN', label: 'Мексиканське песо (MXN)' },
  { code: 'ZAR', label: 'Ренд (ZAR)' },
  { code: 'EGP', label: 'Єгипетський фунт (EGP)' },
  { code: 'THB', label: 'Бат (THB)' },
  { code: 'VND', label: 'Донг (VND)' },
  { code: 'IDR', label: 'Рупія (IDR)' },
  { code: 'MYR', label: 'Малайзійський ринггіт (MYR)' },
  { code: 'BDT', label: 'Така (BDT)' },
  { code: 'DZD', label: 'Алжирський динар (DZD)' },
  { code: 'LBP', label: 'Ліванський фунт (LBP)' },
  { code: 'TND', label: 'Туніський динар (TND)' },
  { code: 'AFN', label: 'Афгані (AFN)' },
  { code: 'ALL', label: 'Албанський лек (ALL)' },
  { code: 'AMD', label: 'Вірменський драм (AMD)' },
  { code: 'ANG', label: 'Нідерландський антильський гульден (ANG)' },
  { code: 'AOA', label: 'Ангольська кванза (AOA)' },
  { code: 'ARS', label: 'Аргентинське песо (ARS)' },
  { code: 'AWG', label: 'Арубський флорин (AWG)' },
  { code: 'BAM', label: 'Конвертована марка (BAM)' },
  { code: 'BBD', label: 'Барбадоський долар (BBD)' },
  { code: 'BGN', label: 'Болгарський лев (BGN)' },
  { code: 'BHD', label: 'Бахрейнський динар (BHD)' },
  { code: 'BIF', label: 'Бурундійський франк (BIF)' },
  { code: 'BMD', label: 'Бермудський долар (BMD)' },
  { code: 'BND', label: 'Брунейський долар (BND)' },
  { code: 'BOB', label: 'Болівіано (BOB)' },
  { code: 'BRL', label: 'Бразильський реал (BRL)' },
  { code: 'BSD', label: 'Багамський долар (BSD)' },
  { code: 'BTN', label: 'Нгултрум (BTN)' },
  { code: 'BWP', label: 'Пула (BWP)' },
  { code: 'BYN', label: 'Білоруський рубль (BYN)' },
  { code: 'BZD', label: 'Белізький долар (BZD)' },
  { code: 'CDF', label: 'Конголезький франк (CDF)' },
  { code: 'CLP', label: 'Чилійське песо (CLP)' },
  { code: 'COP', label: 'Колумбійське песо (COP)' },
  { code: 'CRC', label: 'Костариканський колон (CRC)' },
  { code: 'CUP', label: 'Кубинське песо (CUP)' },
  { code: 'CVE', label: 'Ескудо Кабо-Верде (CVE)' },
  { code: 'DJF', label: 'Джибутійський франк (DJF)' },
  { code: 'DOP', label: 'Домініканське песо (DOP)' },
  { code: 'ERN', label: 'Еритрейська накфа (ERN)' },
  { code: 'ETB', label: 'Ефіопський бир (ETB)' },
  { code: 'FJD', label: 'Фіджійський долар (FJD)' },
  { code: 'FKP', label: 'Фунт Фолклендських островів (FKP)' },
  { code: 'FOK', label: 'Фарерська крона (FOK)' },
  { code: 'GGP', label: 'Гернсійський фунт (GGP)' },
  { code: 'GHS', label: 'Ганський седі (GHS)' },
  { code: 'GIP', label: 'Гібралтарський фунт (GIP)' },
  { code: 'GMD', label: 'Гамбійський даласі (GMD)' },
  { code: 'GNF', label: 'Гвінейський франк (GNF)' },
  { code: 'GTQ', label: 'Гватемальський кетсаль (GTQ)' },
  { code: 'GYD', label: 'Гаянський долар (GYD)' },
  { code: 'HNL', label: 'Гондураська лемпіра (HNL)' },
  { code: 'HTG', label: 'Гаїтянський гурд (HTG)' },
  { code: 'IMP', label: 'Фунт острова Мен (IMP)' },
  { code: 'IQD', label: 'Іракський динар (IQD)' },
  { code: 'IRR', label: 'Іранський ріал (IRR)' },
  { code: 'ISK', label: 'Ісландська крона (ISK)' },
  { code: 'JEP', label: 'Джерсійський фунт (JEP)' },
  { code: 'JMD', label: 'Ямайський долар (JMD)' },
  { code: 'JOD', label: 'Йорданський динар (JOD)' },
  { code: 'KES', label: 'Кенійський шилінг (KES)' },
  { code: 'KGS', label: 'Киргизький сом (KGS)' },
  { code: 'KHR', label: "Камбоджійський р'єль (KHR)" },
  { code: 'KID', label: 'Долар Кірибаті (KID)' },
  { code: 'KMF', label: 'Коморський франк (KMF)' },
  { code: 'KWD', label: 'Кувейтський динар (KWD)' },
  { code: 'KYD', label: 'Долар Кайманових островів (KYD)' },
  { code: 'LAK', label: 'Лаоський кіп (LAK)' },
  { code: 'LKR', label: 'Шрі-ланкійська рупія (LKR)' },
  { code: 'LRD', label: 'Ліберійський долар (LRD)' },
  { code: 'LSL', label: 'Лесотське лоті (LSL)' },
  { code: 'LYD', label: 'Лівійський динар (LYD)' },
  { code: 'MAD', label: 'Марокканський дирхам (MAD)' },
  { code: 'MGA', label: 'Малагасійський аріарі (MGA)' },
  { code: 'MKD', label: 'Македонський денар (MKD)' },
  { code: 'MMK', label: "К'ят (MMK)" },
  { code: 'MNT', label: 'Монгольський тугрик (MNT)' },
  { code: 'MOP', label: 'Патака (MOP)' },
  { code: 'MRU', label: 'Мавританська угія (MRU)' },
  { code: 'MUR', label: 'Маврикійська рупія (MUR)' },
  { code: 'MVR', label: 'Мальдівська руфія (MVR)' },
  { code: 'MWK', label: 'Малавійська квача (MWK)' },
  { code: 'MZN', label: 'Мозамбіцький метикал (MZN)' },
  { code: 'NAD', label: 'Намібійський долар (NAD)' },
  { code: 'NGN', label: 'Нігерійська найра (NGN)' },
  { code: 'NIO', label: 'Нікарагуанська кордоба (NIO)' },
  { code: 'NPR', label: 'Непальська рупія (NPR)' },
  { code: 'OMR', label: 'Оманський ріал (OMR)' },
  { code: 'PAB', label: 'Панамське бальбоа (PAB)' },
  { code: 'PEN', label: 'Перуанський соль (PEN)' },
  { code: 'PGK', label: 'Кіна (PGK)' },
  { code: 'PHP', label: 'Філіппінське песо (PHP)' },
  { code: 'PKR', label: 'Пакистанська рупія (PKR)' },
  { code: 'PYG', label: 'Парагвайський гуарані (PYG)' },
  { code: 'QAR', label: 'Катарський ріал (QAR)' },
  { code: 'RWF', label: 'Руандійський франк (RWF)' },
  { code: 'SBD', label: 'Долар Соломонових Островів (SBD)' },
  { code: 'SCR', label: 'Сейшельська рупія (SCR)' },
  { code: 'SDG', label: 'Суданський фунт (SDG)' },
  { code: 'SHP', label: 'Фунт Святої Єлени (SHP)' },
  { code: 'SLE', label: 'Сьєрра-леонський леоне (SLE)' },
  { code: 'SOS', label: 'Сомалійський шилінг (SOS)' },
  { code: 'SRD', label: 'Суринамський долар (SRD)' },
  { code: 'SSP', label: 'Південносуданський фунт (SSP)' },
  { code: 'STN', label: 'Добра (STN)' },
  { code: 'SYP', label: 'Сирійський фунт (SYP)' },
  { code: 'SZL', label: 'Лілангені (SZL)' },
  { code: 'TJS', label: 'Таджицький сомоні (TJS)' },
  { code: 'TMT', label: 'Туркменський манат (TMT)' },
  { code: 'TOP', label: 'Тонганська паанга (TOP)' },
  { code: 'TTD', label: 'Долар Тринідаду і Тобаго (TTD)' },
  { code: 'TVD', label: 'Долар Тувалу (TVD)' },
  { code: 'TWD', label: 'Новий тайванський долар (TWD)' },
  { code: 'TZS', label: 'Танзанійський шилінг (TZS)' },
  { code: 'UGX', label: 'Угандійський шилінг (UGX)' },
  { code: 'UYU', label: 'Уругвайське песо (UYU)' },
  { code: 'UZS', label: 'Узбецький сум (UZS)' },
  { code: 'VES', label: 'Венесуельський болівар (VES)' },
  { code: 'VUV', label: 'Вануатський вату (VUV)' },
  { code: 'WST', label: 'Самоанська тала (WST)' },
  { code: 'XAF', label: 'Франк КФА BEAC (XAF)' },
  { code: 'XCD', label: 'Східнокарибський долар (XCD)' },
  { code: 'XCG', label: 'Карибський гульден (XCG)' },
  { code: 'XOF', label: 'Франк КФА BCEAO (XOF)' },
  { code: 'XPF', label: 'Тихоокеанський франк (XPF)' },
  { code: 'YER', label: 'Єменський ріал (YER)' },
  { code: 'ZMW', label: 'Замбійська квача (ZMW)' },
  { code: 'ZWG', label: 'Зімбабвійський золотий (ZWG)' },
]
